export const SHOW_TOAST = 'SHOW_TOAST'
export const API = 'API'
export const API_START = 'API_START'
export const API_END = 'API_END'
export const GET_REPOS = 'GET_REPOS'
export const SET_REPOS = 'SET_REPOS'
